services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5087:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=ecommerce-RO;Username=postgres;Password=vovolili1234
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vovolili1234
      POSTGRES_DB: ecommerce-RO
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data: